version: '3.7'
services:
  mojo:
    container_name: nhs-mojo
    volumes:
      - ./mojo:/run/nhs:ro
    build:
      context: ./mojo
      dockerfile: ./Dockerfile
      target: build-small
    ports:
      - 8081:8081
    environment:
      - PERL5LIB=/cpan-mods/lib/perl5
    depends_on:
      - database
      - feeder
      - mojo-cpan

  feeder:
    container_name: nhdb-feeder
    volumes:
      - ./feeder:/run/nhs:ro
      - xlogs_vol:/var/log/xlogs:rw
    environment:
      - PERL5LIB=/cpan-mods/lib/perl5
    build:
      context: ./feeder
      dockerfile: ./Dockerfile
      target: build-small
    depends_on:
      - database
      - feeder-base
      - feeder-cpan

  database:
    container_name: nhs-db
    logging: 
      driver:
        none
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    command: ['postgres', '-c', 'log_statement=none', '-c', 'checkpoint_completion_target=0.9']
    volumes:
      - db_vol:${PGDATA}:rw
    env_file:
      - ./postgres/env
    ports:
      - 5433:5433

  feeder-cpan:
    image: feeder-cpan-mods:latest
    build:
      context: ./feeder
      dockerfile: ./Dockerfile
      target: build-cpan-deps
    depends_on:
      - cpan
      - feeder-base

  mojo-cpan:
    image: mojo-cpan-mods:latest
    build:
      context: ./mojo
      dockerfile: ./Dockerfile
      target: build-cpan-deps
    depends_on:
      - cpan
      - mojo-base

  cpan:
    image: cpan:latest
    build:
      context: ./cpan
      dockerfile: ./Dockerfile

  feeder-base:
    image: feeder-bin-libs:latest
    build:
      context: ./feeder
      dockerfile: ./Dockerfile
      target: install-bin-deps

  mojo-base:
    image: mojo-bin-libs:latest
    build:
      context: ./mojo
      dockerfile: ./Dockerfile
      target: install-bin-deps

volumes:
  db_vol:
  xlogs_vol:
