version: '3.7'
services:
  database:
    container_name: nhs-db
    logging: 
      driver:
        none
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    command: ['postgres', '-c', 'log_statement=none', '-c', 'checkpoint_completion_target=0.9']
    volumes:
      - db_vol:${PGDATA}:rw
    env_file:
      - ./postgres/env
    ports:
      - 5432:5432

  mojo-web:
    container_name: nhs-web-m
    volumes:
      - ./mojo:/run/nhs:ro
    build:
      context: ./mojo
      dockerfile: ./Dockerfile
      target: run-mojo
    ports:
      - 8082:8082

  feeder:
    container_name: nhdb-feeder
    volumes:
      - ./legacy:/run/nhs:ro
      - xlogs_vol:/var/log/xlogs:rw
    build:
      context: ./legacy
      dockerfile: ./Dockerfile
      target: run-feeder

  base:
    image: perl-base
    build:
      context: ./
      dockerfile: ./Dockerfile

  libs-legacy:
    image: cpan-moo
    build:
      context: ./legacy
      dockerfile: ./Dockerfile
      target: install-cpan-legacy

  libs-mojo:
    image: cpan-mojo
    build:
      context: ./mojo
      dockerfile: ./Dockerfile
      target: install-cpan-mojo

volumes:
  db_vol:
  xlogs_vol:
