version: '3.7'
services:
  database:
    container_name: nhs_postgres
    logging: 
      driver:
        none
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    command: ['postgres', '-c', 'log_statement=none', '-c', 'checkpoint_completion_target=0.9']
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${PGDATA}
    volumes:
      - db_vol:${PGDATA}:rw
    env_file:
      - ./docker/environment/database.env
    ports:
      - 5432:5432
  base:
    build:
      context: ./
      dockerfile: ./docker/perl/Dockerfile.base
  cpan:
    build:
      context: ./
      dockerfile: ./docker/perl/Dockerfile.cpan
  mojo:
    container_name: nhs_mojo
    volumes:
      - ./public:/nhs/public:ro
      - ./logs:/nhs/logs:rw
      - ./templates:/nhs/templates:ro
      - ./script:/nhs/script:ro
      - ./lib:/nhs/lib:ro
    build:
      context: ./
      dockerfile: ./docker/perl/Dockerfile.mojo
    env_file:
      - ./docker/environment/database.env
    ports:
      - '8082:8082'
volumes:
  db_vol:
