version: '3.7'
services:
  database:
    container_name: nhs_postgres
    logging: 
      driver:
        none
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    command: ['postgres', '-c', 'log_statement=none', '-c', 'checkpoint_completion_target=0.9']
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${PGDATA}
    env_file:
      - ./docker/environment/database.env
    ports:
      - 5432:5432
  perl:
    container_name: nhs_perl
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./docker/perl/Dockerfile
    command: ['morbo', 'script/net_hack_stats']
    env_file:
      - ./docker/environment/database.env
    ports:
      - '8082:8082'
